== MicroProfile JWT on Quarkus

This demo project illustrates how to secure a REST API on Quarkus with MicroProfile JWT.


=== Maven configuration

In contrast to Open Liberty and Wildfly, there is no independant runtime (aka Application Server) with Quarkus. The runtime configuration is embedded with the application and determined from the Maven configuration. 

For this project, resteasy, quarkus-smallrye-openapi and quarkus-smallrye-jwt must be declared as a dependencies.


=== Application configuration

==== application.properties
With Quarkus, application.properties acts as the central configuration file. The public key value and the issuer must be copied from the microprofile-config.properties generated by JWTenizr:
[source, text]
----
mp.jwt.verify.publickey=<public key here>
mp.jwt.verify.issuer=jefrajames
mp.jwt.verify.requireiss=true
quarkus.smallrye-jwt.enabled=true
----

=== Coding

With Quarkus, no JAX-RS application class is needed. Hence there is no @LoginConfig annotation.

Arquillian is not needed to run Junit Tests with Quarkus:

. The @QuarkusTest annotation is sufficient
. No ShrinkWrap deployment is needed.

Ease of test is a real bonus with Quarkus!

=== Playing around

. To run Quarkus in dev mode (with hot reload) : mvn compile quarkus:dev 
. To run the Junit Tests: mvn test
. The app URL is http://localhost:8080/hello/
. To curl against the app: curl.sh, curl.sh secured, curl.sh forbidden, curl.sh myclaim
. To access Swagger UI: http://localhost:8080/swagger-ui/
. To package the app in JVM mode: mvn package
. To package the app in native excutable: mvn package -Pnative.

=== Which HTTP response code?

* Expired token: 401 (Unauthorized)
* Role not allowed: 403 (Forbidden)
* Issuer mismatch: 401 (Unauthorized)

=== Quarkus tricks

Here are some tricks regarding Quarkus behavior:

* In the absence of any MP JWT configuration in application.properties, all API calls are rejected with 401 (Unauthorized)
* If quarkus.smallrye-jwt.enabled=false:
** API calls on methods secured with @RolesAllowed are rejected with 403 (forbidden), even with correct tokens!
** Other API calls work as expected
* To check the issuer claim: mp.jwt.verify.requireiss must be set to true [underline]#AND# mp.jwt.verify.requireiss must be defined:
** If mp.jwt.verify.requireiss=false: the issuer claim is not checked
** If mp.jwt.verify.requireiss=true and mp.jwt.verify.issuer is not defined: the issuer claim is not checked
* Quarkus provides 60 seconds of leeway to account for clock skew when checking token expiration
* When things go wrong, Quarkus is not very talkative. For instance, the same 401 response is sent when the public key is badly configured or when a token is wrong (expired, issuer mismatch...), but no log message helps identify the root cause. To make a diagnostic, it is necessary to increase the default log level: quarkus.log.level=FINEST
* To enable swagger-ui in all modes (dev, test, prod) quarkus.swagger-ui.always-include must be set to true
* Setting @DenyAll at the JAX-RS resource class level has the effect of rejecting all API calls with 403 (Forbidden). This may be a bug.
